# #########################################################################
#
# NOTE:
# This workflow serves to run the unit tests on push and pull requrest.
# The workflow is replicated in <root>/tox.ini to serve as a way
# to run the same test worklow from a local development enviornment.  If
# any changes are made here, the same changes need to be propogated to
# tox.ini
#
# #########################################################################

---
name: test
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt

      - name: link with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 pureport_client/ test/  --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 pureport_client/ test/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: test with pytest
        run: |
          pytest --cov='pureport_client' --cov-append -v test/
